---
title: "merge_Limma_and_MaAsLin2"
author: "jialh"
date: "2024-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. 读取数据
加载所需的包：
```{r}
library(stringr)
library(ggplot2)
library(ggrepel)
```

读取MaAsLin2差异丰度分析的结果:
```{r cars}
workdir="D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_validation"
inputdir="D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_validation"
A_df = read.csv(file.path(inputdir, "species",  "MaAsLin2_Archaea_allvsNC.csv"))
B_df = read.csv(file.path(inputdir, "species", "MaAsLin2_Bacteria_allvsNC.csv"))
F_df = read.csv(file.path(inputdir, "species", "MaAsLin2_Fungi_allvsNC.csv"))
V_df = read.csv(file.path(inputdir, "species", "MaAsLin2_Viruses_allvsNC.csv"))

A_df_wide <- reshape(A_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
B_df_wide <- reshape(B_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
F_df_wide <- reshape(F_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
V_df_wide <- reshape(V_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
#diff_df1$species_name = sub(".*s__", "",  diff_df1$species)
diff_df1 = rbind(A_df_wide, B_df_wide, F_df_wide, V_df_wide)
diff_df1$feature = gsub(".k__", "|k__", diff_df1$feature)
diff_df1$feature = gsub(".p__", "|p__", diff_df1$feature)
diff_df1$feature = gsub(".c__", "|c__", diff_df1$feature)
diff_df1$feature = gsub(".o__", "|o__", diff_df1$feature)
diff_df1$feature = gsub(".f__", "|f__", diff_df1$feature)
diff_df1$feature = gsub(".g__", "|g__", diff_df1$feature)
diff_df1$feature = gsub(".s__", "|s__", diff_df1$feature)
print(colnames(diff_df1))
diff_df1 = diff_df1[, c("feature", "coef.SCS", "qval.SCS", "coef.SCD", "qval.SCD", "coef.MCI", "qval.MCI", "coef.AD", "qval.AD")]
write.csv(diff_df1, file.path(inputdir, "species",  "MaAsLin2_species_allvsNC.csv"), row.names=FALSE)
diff_df1[is.na(diff_df1)] = 1.0
diff_df1$species = diff_df1$feature
```

读取Limma的差异丰度分析结果:

```{r pressure, echo=FALSE}
inputdir = "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03Limma_diff"
A_df = read.csv(file.path(inputdir, "species",  "Limma_Archaea_allstagesvsNC.csv"))
B_df = read.csv(file.path(inputdir, "species", "Limma_Bacteria_allstagesvsNC.csv"))
F_df = read.csv(file.path(inputdir, "species", "Limma_Fungi_allstagesvsNC.csv"))
V_df = read.csv(file.path(inputdir, "species", "Limma_Viruses_allstagesvsNC.csv"))
diff_df2 = rbind(A_df, B_df, F_df, V_df)
diff_df2$species = diff_df2$X
diff_df2[is.na(diff_df2)] = 1.0
```
合并两种方法的结果:
```{r}
##https://stackoverflow.com/questions/17215789/extract-a-substring-according-to-a-pattern
merge_diff = merge(diff_df1, diff_df2, by.x="species", by.y="species", all=TRUE)
merge_diff[is.na(merge_diff)] = 1.0
print(colnames(merge_diff)[grepl('AD', colnames(merge_diff))])

mytheme <- theme(
            panel.grid.minor.x = element_blank(),
            panel.grid.minor.y = element_blank(), 
            legend.position="top", 
            axis.text.x = element_text(size=10, hjust = 0.5, family="serif"),
            axis.title.x = element_text(size = 12, family="serif"),
            axis.text.y = element_text(size = 10, family="serif"),
            axis.title.y = element_text(size = 12, family="serif"),
            plot.title = element_text(family="serif", hjust=0.5, size=12),
            plot.subtitle = element_text(family="serif", hjust=0.5, size=12),
            strip.text.x = element_text(family="serif", size=12),
            legend.text=element_text(family="serif", size=10),
            legend.title=element_blank()
            )
```


合并两种差异丰度分析方法:
- 对坐标轴进行对数变化: http://www.sthda.com/english/wiki/ggplot2-axis-scales-and-transformations
```{r fig.width=4, fig.height=4}
colors = c("#ff6836", "#36bccb", "#999999")
merge_diff$AD_association = 'Not associated'
merge_diff$AD_association[(merge_diff$qval.AD<0.25) & (merge_diff$AD_adj.P.Val<0.1) & (merge_diff$AD_logFC >0)] = 'Elevation'
merge_diff$AD_association[(merge_diff$qval.AD<0.25) & (merge_diff$AD_adj.P.Val<0.1) & (merge_diff$AD_logFC <0)] = 'Depletion'

merge_diff$AD_association = factor(merge_diff$AD_association, levels=c('Elevation', 'Depletion', 'Not associated'))
x_axis_values = c(0, -log10(0.25), -log10(0.05), 2, 4)
x_axis_labels = c(1, 0.25, 0.05, 0.01, 1e-4)

y_axis_values = c(0, -log10(0.1), -log10(0.01), 4, 6)
y_axis_labels = c(1, 0.1, 0.01, 1e-4, 1e-6)
print(table(merge_diff$AD_association))
p1 <- ggplot (data = merge_diff, aes(x = -log10(qval.AD + 1e-6), y = -log10(AD_adj.P.Val + 1e-6), colour = AD_association))+  
      geom_point(size=2) +
      scale_color_manual(values=colors) + 
      geom_vline(xintercept = -log10(0.25), linetype = "dashed", color = "grey", linewidth=1) +
      geom_hline(yintercept = 1, linetype = "dashed", color = "grey", linewidth=1) + 
      geom_text_repel(aes(label=ifelse(AD_association %in% c('Elevation', 'Depletion'), sub(".*s__", "", species),'')), hjust = -0.1,  vjust = 0.5, size=3) + 
      labs(x="-log10(MaAsLin2\ FDR)", y="-log10(Limma\ FDR)", title="AD-associated species") +
      scale_x_continuous(breaks= x_axis_values, labels=x_axis_labels, limits=c(-0.1, 4.2)) + 
      scale_y_continuous(breaks= y_axis_values, labels=y_axis_labels, limits=c(-0.1, 6.2)) +
      theme_bw() + 
      mytheme
print(p1) # 或者 print (p1)
```


```{r fig.width=4, fig.height=4}
# colors = c("#ff6836", "#36bccb", "#999999")
merge_diff$MCI_association = 'Not associated'
merge_diff$MCI_association[(merge_diff$qval.MCI<0.25) & (merge_diff$MCI_adj.P.Val<0.1) & (merge_diff$MCI_logFC >0)] = 'Elevation'
merge_diff$MCI_association[(merge_diff$qval.MCI<0.25) & (merge_diff$MCI_adj.P.Val<0.1) & (merge_diff$MCI_logFC <0)] = 'Depletion'
print(table(merge_diff$MCI_association))
selected_columns = colnames(merge_diff)[grepl('MCI', colnames(merge_diff))]
print(merge_diff[(merge_diff$qval.MCI<0.25) & (merge_diff$MCI_adj.P.Val<0.1), selected_columns])
if(length(unique(merge_diff$MCI_association))==2){
    merge_diff$MCI_association = factor(merge_diff$MCI_association, levels=c('Elevation', 'Not associated'))
    colors = c("#ff6836",  "#999999")
}
x_axis_values = c(0, -log10(0.25), -log10(0.05), 2, 4)
x_axis_labels = c(1, 0.25, 0.05, 0.01, 1e-4)

y_axis_values = c(0, -log10(0.1), -log10(0.01), 4, 6)
y_axis_labels = c(1, 0.1, 0.01, 1e-4, 1e-6)
p2 <- ggplot (data = merge_diff, aes(x = -log10(qval.MCI + 1e-6), y = -log10(MCI_adj.P.Val + 1e-6), colour = MCI_association))+  
      geom_point(size=2, position=position_jitter(width =0.1, height=0.1)) +
      scale_color_manual(values=colors) + 
      geom_vline(xintercept = -log10(0.25), linetype = "dashed", color = "grey", linewidth=1) +
      geom_hline(yintercept = 1, linetype = "dashed", color = "grey", linewidth=1) + 
      geom_text_repel(aes(label=ifelse(MCI_association %in% c('Elevation', 'Depletion'), sub(".*s__", "", species),'')), hjust = -0.1,  vjust = 0.5, size=3) + 
      labs(x="-log10(MaAsLin2\ FDR)", y="-log10(Limma\ FDR)", title="MCI-associated species") +
      scale_x_continuous(breaks= x_axis_values, labels=x_axis_labels, limits=c(-0.1, 4.2)) + 
      scale_y_continuous(breaks= y_axis_values, labels=y_axis_labels, limits=c(-0.1, 6.2)) +
      theme_bw() + 
      mytheme
print(p2) # 或者 print (p1)
```

```{r fig.width=4, fig.height=4}
#colors = c("#ff6836", "#36bccb", "#999999")
merge_diff$SCD_association = 'Not associated'
merge_diff$SCD_association[(merge_diff$qval.SCD<0.25) & (merge_diff$SCD_adj.P.Val<0.1) & (merge_diff$SCD_logFC >0)] = 'Elevation'
merge_diff$SCD_association[(merge_diff$qval.SCD<0.25) & (merge_diff$SCD_adj.P.Val<0.1) & (merge_diff$SCD_logFC <0)] = 'Depletion'

if(length(unique(merge_diff$SCD_association))==1){
    merge_diff$SCD_association = factor(merge_diff$SCD_association, levels=c('Not associated'))
    colors = c("#999999")
}

x_axis_values = c(0, -log10(0.25), -log10(0.05), 2, 4)
x_axis_labels = c(1, 0.25, 0.05, 0.01, 1e-4)

y_axis_values = c(0, -log10(0.1), -log10(0.01), 4, 6)
y_axis_labels = c(1, 0.1, 0.01, 1e-4, 1e-6)
print(table(merge_diff$SCD_association))
p3 <- ggplot (data = merge_diff, aes(x = -log10(qval.SCD + 1e-6), y = -log10(SCD_adj.P.Val + 1e-6), colour = SCD_association))+  
      geom_point(size=2) +
      scale_color_manual(values=colors) + 
      geom_vline(xintercept = -log10(0.25), linetype = "dashed", color = "grey", linewidth=1) +
      geom_hline(yintercept = 1, linetype = "dashed", color = "grey", linewidth=1) + 
      geom_text_repel(aes(label=ifelse(SCD_association %in% c('Elevation', 'Depletion'), sub(".*s__", "", species),'')), hjust = -0.1,  vjust = 0.5, size=3) + 
      labs(x="-log10(MaAsLin2\ FDR)", y="-log10(Limma\ FDR)", title="SCD-associated species") +
      scale_x_continuous(breaks= x_axis_values, labels=x_axis_labels, limits=c(-0.1, 4.2)) + 
      scale_y_continuous(breaks= y_axis_values, labels=y_axis_labels, limits=c(-0.1, 6.2)) +
      theme_bw() + 
      mytheme
print(p3) # 或者 print (p1)
```
```{r fig.width=4, fig.height=4}
colors = c("#ff6836", "#36bccb", "#999999")
merge_diff$SCS_association = 'Not associated'
merge_diff$SCS_association[(merge_diff$qval.SCS<0.25) & (merge_diff$SCS_adj.P.Val<0.1) & (merge_diff$SCS_logFC >0)] = 'Elevation'
merge_diff$SCS_association[(merge_diff$qval.SCS<0.25) & (merge_diff$SCS_adj.P.Val<0.1) & (merge_diff$SCS_logFC <0)] = 'Depletion'

if(length(unique(merge_diff$MCI_association))==1){
    merge_diff$MCI_association = factor(merge_diff$MCI_association, levels=c('Not associated'))
    colors = c("#999999")
}

x_axis_values = c(0, -log10(0.25), -log10(0.05), 2, 4)
x_axis_labels = c(1, 0.25, 0.05, 0.01, 1e-4)

y_axis_values = c(0, -log10(0.1), -log10(0.01), 4, 6)
y_axis_labels = c(1, 0.1, 0.01, 1e-4, 1e-6)
print(table(merge_diff$SCS_association))
p4 <- ggplot (data = merge_diff, aes(x = -log10(qval.SCS + 1e-6), y = -log10(SCS_adj.P.Val + 1e-6), colour = SCS_association))+  
      geom_point(size=2) +
      scale_color_manual(values=colors) + 
      geom_vline(xintercept = -log10(0.25), linetype = "dashed", color = "grey", linewidth=1) +
      geom_hline(yintercept = 1, linetype = "dashed", color = "grey", linewidth=1) + 
      geom_text_repel(aes(label=ifelse(SCS_association %in% c('Elevation', 'Depletion'), sub(".*s__", "", species),'')), hjust = -0.1,  vjust = 0.5, size=3) + 
      labs(x="-log10(MaAsLin2\ FDR)", y="-log10(Limma\ FDR)", title="SCS-associated species") +
      scale_x_continuous(breaks= x_axis_values, labels=x_axis_labels, limits=c(-0.1, 4.2)) + 
      scale_y_continuous(breaks= y_axis_values, labels=y_axis_labels, limits=c(-0.1, 6.2)) +
      theme_bw() + 
      mytheme
print(p4) # 或者 print (p1)
```
合并四张子图:
```{r}
library(ggpubr)
outdir = "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff"
pdf(file.path(outdir, "merge_diff_species_from_MaAsLin2_and_Limma_20240629.pdf"), width=8, height=8)
merge_img = ggarrange(p4, p3, p2, p1, nrow=2, ncol=2, align="hv", common.legend=TRUE, labels=letters[1:4])
print(merge_img)
dev.off()
```

