---
title: "metaAD_analysis"
output:
  html_document: default
  pdf_document: default
date: "2023-03-19"
editor_options: 
  chunk_output_type: console
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
####################################################################################################
## 4. MaAsLin2的可视化热图###########################################################################
####################################################################################################
```{r}
library(ComplexHeatmap)
library(circlize)
library(rlist)
library(VennDiagram)
library(dplyr)
# taxon_types = c('species', "KOs", 'pathways', 'GMMs', 'GBMs')
taxon_types = c("KOs", "pathways")
for (taxon_type in taxon_types){
    print(paste0("deal with ", taxon_type))
    workdir <- "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom"
    inputdir <- file.path(workdir, "03MaAsLin2_validation", taxon_type)
    outdir <- file.path(workdir, "03MaAsLin2_validation", taxon_type)
    dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
    if(taxon_type=="species"){
        A_df = read.csv(file.path(inputdir, "MaAsLin2_Archaea_allvsNC.csv"))
        B_df = read.csv(file.path(inputdir, "MaAsLin2_Bacteria_allvsNC.csv"))
        F_df = read.csv(file.path(inputdir, "MaAsLin2_Fungi_allvsNC.csv"))
        V_df = read.csv(file.path(inputdir, "MaAsLin2_Viruses_allvsNC.csv"))
        A_df_wide <- reshape(A_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
        B_df_wide <- reshape(B_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
        F_df_wide <- reshape(F_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
        V_df_wide <- reshape(V_df[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
        #validation_df1$species_name = sub(".*s__", "",  validation_df1$species)
        diff_df = rbind(A_df_wide, B_df_wide, F_df_wide, V_df_wide)
        diff_df[is.na(diff_df)] = 1.0
        diff_df$feature = gsub(".k__", "|k__", diff_df$feature)
        diff_df$feature = gsub(".p__", "|p__", diff_df$feature)
        diff_df$feature = gsub(".c__", "|c__", diff_df$feature)
        diff_df$feature = gsub(".o__", "|o__", diff_df$feature)
        diff_df$feature = gsub(".f__", "|f__", diff_df$feature)
        diff_df$feature = gsub(".g__", "|g__", diff_df$feature)
        diff_df$feature = gsub(".s__", "|s__", diff_df$feature)
        write.csv(diff_df, file.path(outdir, paste0("MaAsLin2_", taxon_type, "_merge.csv")), row.names=FALSE)
        threshold = 0.25
    }else{
        diff_df_long = read.csv(file.path(inputdir, paste0("MaAsLin2_", taxon_type, "_allvsNC.csv")))
        diff_df = reshape(diff_df_long[, c("feature", "value", "coef", "qval")], idvar = "feature", timevar = "value", direction = "wide")
        diff_df[is.na(diff_df)] = 1.0
        write.csv(diff_df, file.path(outdir, paste0("MaAsLin2_", taxon_type, "_merge.csv")), row.names=FALSE)
        if(taxon_type=="KOs"){
            threshold = 0.10
        }else{
            threshold = 0.10
        }
    }
    
    row.names(diff_df) = diff_df$feature
    MaAsLin2_stat <- data.frame()
    MaAsLin2_features <- list()
    MaAsLin2_features_merge <- list()
    stages = c("SCS", "SCD", "MCI", "AD")
    #feat_types = c("A", "B", "F", "V")
    #feat_types = c("KOs")
    study = "CHN+CHN2"
    for (stage in stages){
        ##注意图2d中最终选择的差异KOs阈值是0.01。
        diff_count = nrow(diff_df[(diff_df[paste0("qval.", stage)] < threshold) , ])
        diff_species = row.names(diff_df[(diff_df[paste0("qval.", stage)] < threshold), ])
        MaAsLin2_stat[taxon_type, paste0("NC_vs_", stage)] = diff_count
        MaAsLin2_features[[paste0("NC_vs_", stage, "_", taxon_type)]] <- diff_species
        MaAsLin2_features_merge <- c(MaAsLin2_features_merge, diff_species)
    }
    
    # print(MaAsLin2_stat)
    # print(MaAsLin2_features)
    write.csv(MaAsLin2_stat, file.path(outdir, "MaAsLin2_stat.csv"))
    #source("D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\statistic\\pipelines\\03MaAsLin2_diff.R")
    #MaAsLin2_stat_plot(workdir, MaAsLin2_stat, MaAsLin2_features)
    
    MaAsLin2_features_merge <- unlist(MaAsLin2_features_merge)
    MaAsLin2_features_df <- as.data.frame(table(MaAsLin2_features_merge))
    MaAsLin2_features_df_sort <- MaAsLin2_features_df[order(MaAsLin2_features_df$Freq, decreasing = TRUE),]
    MaAsLin2_features_outfile <- file.path(outdir, "MaAsLin2_features_merge.csv")
    write.csv(MaAsLin2_features_df_sort, MaAsLin2_features_outfile, row.names = FALSE)
}
```
MaAsLin2的可视化热图
```{r}
rm(list=ls())
taxon_type = "KOs"
workdir="D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom"
#workdir="D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom"
#source("D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\statistic\\01preprocess\\00load_data.R")
infile = file.path(workdir, "00profile", paste0("metadata_", taxon_type, ".csv"))
metadata_taxon <- data.table::fread(infile, sep=",",  header=TRUE, stringsAsFactors = FALSE)
metadata_taxon <- as.data.frame(metadata_taxon)
row.names(metadata_taxon) <- metadata_taxon$Sample
metadata_taxon_filter = metadata_taxon[metadata_taxon$Batch %in% c('CHN', 'CHN2'), ]
metadata_taxon$Group <- factor(metadata_taxon$Group, levels = c("NC", "SCS", "SCD", "MCI", "AD"))


metadata <- metadata_taxon_filter[, 1:15]
taxon <- metadata_taxon_filter[, 16:ncol(metadata_taxon)]
script_dir <- "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\statistic"
source(file.path(script_dir, "01preprocess", "01feature_prepare.R"))
if (taxon_type == "species"){
    taxon_rel_filter = merge_feats(taxon, feat_type="ABFV", min_abundance=1e-4, min_prevalence=0.1)
}else if(taxon_type %in% c("KOs", "pathways", "GMMs", "GBMs")){
    taxon_rel_filter = merge_feats(taxon, feat_type=taxon_type, min_abundance=1e-6, min_prevalence=0.1)
}
#taxon_rel_filter = merge_feats(taxon, feat_type="ABFV", min_abundance=1e-4, min_prevalence=0.1)

##统计古细菌、细菌、真菌和病毒的数量。
if(taxon_type=="species"){
    print(dim(taxon_rel_filter[, grepl("k__Archaea", colnames(taxon_rel_filter))]))  ##70
    print(dim(taxon_rel_filter[, grepl("k__Bacteria", colnames(taxon_rel_filter))]))  ##318
    print(dim(taxon_rel_filter[, grepl("k__Fungi", colnames(taxon_rel_filter))]))    ##37
    print(dim(taxon_rel_filter[, grepl("k__Viruses", colnames(taxon_rel_filter))]))  ##48
}
#print(length(unique(colnames(taxon_rel_filter))))

print(colnames(metadata))
print(colnames(taxon)[1:5])
```
所选特征的Heatmap分析展示:
```{r}
#remove(list=ls())
library(stringr)
library(ComplexHeatmap)
inputdir = "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff"
#dev.off()
if(taxon_type=="KOs"){
    infile = file.path(inputdir, taxon_type, "MaAsLin2_features_merge.csv")
    diff_taxon_df <-read.csv(infile, header=1)
    taxon_list <- diff_taxon_df[diff_taxon_df['Freq']>=1, 'MaAsLin2_features_merge']
}else if(taxon_type=="species"){
    infile = file.path(inputdir, taxon_type, "MaAsLin2_features_merge.csv")
    diff_taxon_df <-read.csv(infile, header=1)
    taxon_list <- diff_taxon_df[diff_taxon_df['Freq']>=1, 'MaAsLin2_features_merge']
}else{
    infile = file.path(inputdir, taxon_type, "MaAsLin2_features_merge.csv")
    diff_taxon_df <-read.csv(infile, header=1)
    taxon_list <- diff_taxon_df[diff_taxon_df['Freq']>=1, 'MaAsLin2_features_merge']
}

taxon_rel_selected <- taxon_rel_filter[, colnames(taxon_rel_filter) %in% taxon_list]


meta_taxon_rel_selected <- merge(metadata, taxon_rel_selected, by.x="row.names", by.y="row.names")
meta_taxon_rel_selected$Group <- factor(meta_taxon_rel_selected$Group, levels=c("NC", "SCS", "SCD", "MCI", "AD"))

row.names(meta_taxon_rel_selected) = meta_taxon_rel_selected$Row.names
features = meta_taxon_rel_selected[,17:ncol(meta_taxon_rel_selected)]
feat.all = t(features)
```

将丰度表转化为generalized fold change

```{r}
##参考代码: https://github.com/zellerlab/crc_meta/blob/master/src/marker_analysis.R#L67
stages = c("SCS", "SCD", "MCI", "AD")
gFC = matrix(NA, nrow=nrow(feat.all), ncol=length(stages), 
                dimnames=list(row.names(feat.all), stages))

for (feature in row.names(feat.all)){
  
  # for each study
  for (stage in stages) {
    #feature = row.names(feat.all)[1]
    #stage = "AD"
    ##########################################
    case_abundance <- feat.all[feature, metadata %>% 
                    filter(Group==stage) %>% pull(Sample)]
    NC_abundance <- feat.all[feature, metadata %>% 
                    filter(Group=='NC') %>% pull(Sample)]
    
    # # Wilcoxon
    # p.val[f,s] <- wilcox.test(NC_abundance, y, exact=FALSE)$p.value
    # 
    # # AUC
    # aucs.all[[f]][[s]] <- c(roc(controls=y, cases=x, 
    #                             direction='<', ci=TRUE, auc=TRUE)$ci)
    # aucs.mat[f,s] <- c(roc(controls=y, cases=x, 
    #                        direction='<', ci=TRUE, auc=TRUE)$ci)[2]
    if(taxon_type == "species"){
        log.n0 = 1e-6
    }else if(taxon_type %in% c("KOs", "pathways", "GMMs", "GBMs")){
        log.n0 = 1e-8
    }
    
    # FC
    q.case <- quantile(log10(case_abundance+log.n0), probs=seq(.1, .9, .05))
    q.NC <- quantile(log10(NC_abundance+log.n0), probs=seq(.1, .9, .05))
    fold_change <- sum(q.case - q.NC)/length(q.case)
    gFC[feature, stage] <- fold_change
  }
}


#gFC <- gFC[rowSums(abs(gFC)>0.05)>=1, ]
unmapped_species <- setdiff(diff_taxon_df$MaAsLin2_features_merge, row.names(gFC))
print(unmapped_species)
print(unmapped_species[1] %in% colnames(taxon_rel_filter))
print(unmapped_species[2] %in% colnames(taxon_rel_filter))
```

准备热图中的符号:
```{r}
graphlandir = file.path("D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff", taxon_type)
if(taxon_type == "KOs"){
    coef_df = read.csv(file.path(graphlandir, "MaAsLin2_diff_merge.csv"), header=TRUE, row.names=1)
    qval_df = read.csv(file.path(graphlandir, "MaAsLin2_diff_qvalue.csv"), header=TRUE, row.names=1)
}else{
    coef_df = read.csv(file.path(graphlandir, "MaAsLin2_diff_merge.csv"), header=TRUE, row.names=1)
    qval_df = read.csv(file.path(graphlandir, "MaAsLin2_diff_qvalue.csv"), header=TRUE, row.names=1)
}

###
colnames(coef_df) = gsub("coef.", "", colnames(coef_df))
colnames(qval_df) = gsub("qval.", "", colnames(qval_df))
all.equal(row.names(coef_df), row.names(qval_df), check.attributes = FALSE)
all.equal(colnames(coef_df), colnames(qval_df), check.attributes = FALSE)
all.equal(row.names(coef_df), row.names(gFC), check.attributes = FALSE)

##
marker_df = coef_df
for(row in rownames(coef_df)){
    for(col in colnames(coef_df)){
        coef = coef_df[row, col]
        qval = qval_df[row, col]
        #print(paste0("coef: ", coef, ", qval: ", qval))
        if((!is.na(coef)) & (!is.na(qval))){
            #print(paste0("coef: ", coef, ", qval: ", qval))
            if(coef>0 & qval<0.1){
                marker_df[row, col] = "+"
            }else if(coef<0 & qval<0.1){
                marker_df[row, col] = "-"
            }
        }
    }
}
#print(marker_df)
# marker_df$NC = ""
marker_df = marker_df[, c("SCS", "SCD", "MCI", "AD")]
marker_df[is.na(marker_df)] = ""
marker_df_filter = marker_df[row.names(gFC), ]
qval_df_filter = qval_df[row.names(gFC),]
rownames(marker_df_filter) <- gsub('^k__.*s__', '', rownames(marker_df_filter), perl = TRUE)
```
给热图加上所属的pathways和module信息
```{r}
library(dplyr)
library(stringi)
library(cowplot)
library(ggplot2)
outdir=file.path("D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff", taxon_type)
boxplotdir = file.path(outdir, 'boxplot')
dir.create(boxplotdir, showWarnings = FALSE)
inputdir="D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\00profile"
#diff_df = read.csv(file.path(workdir, "02diff_KO", "01wilcox_test_KO_features0.05.csv"), header=TRUE)
#diff_df_filter = diff_df[diff_df$value<0.005, ]
#print(diff_df_filter[1:5, ])

diff_df_filter = as.data.frame(gFC)
diff_df_filter$feature = row.names(gFC)

###
KOs_desc = read.csv(file.path(inputdir, "KEGG_KOs_to_pathways_metabolism.csv"), header=1, row.names=1)
KOs_desc$KO_short_name = stringr::str_split_fixed(KOs_desc$KO_name, ";", n=2)[,1]
KOs_desc$Pathway_category2_short = stringr::str_split_fixed(KOs_desc$Pathway_category2, " ", n=2)[,2]
diff_df_filter = merge(diff_df_filter, KOs_desc, by.x="row.names", by.y="row.names")


##
library(stringr)
write.csv(diff_df_filter, file.path(outdir, paste0("01MaAsLin2_features.filter.csv")))
print(diff_df_filter[1:5, ])

# print(diff_df_filter[diff_df_filter$KO_short_name %in% c("K02586  nifD", "K02591  nifK"), ])
# print(diff_df_filter[diff_df_filter$map=="map00910", ])
####
diff_df_filter$Pathway_short_name[diff_df_filter$KO_short_name %in% c("K02586  nifD", "K02591  nifK")] = "Nitrogen metabolism"
diff_df_filter$Pathway_category2_short[diff_df_filter$KO_short_name %in% c("K02586  nifD", "K02591  nifK")] = "Energy metabolism"
#diff_df_filter$Pathway_short_name[diff_df_filter$KO_short_name %in% c("K02586  nifD", "K02591  nifK")] == "Nitrogen metabolism"
```

```{r}
meta_feats_rel_merge = diff_df_filter
#print(meta_feats_rel_merge)
print(dim(meta_feats_rel_merge))

pathway_count = data.frame(table(meta_feats_rel_merge$Pathway_short_name))
colnames(pathway_count) = c("pathway", "count")
pathway_count_filter = pathway_count[pathway_count$count>=2, ]
selected_pathways = unique(pathway_count_filter$pathway)
print(selected_pathways)
meta_feats_rel_merge = meta_feats_rel_merge[meta_feats_rel_merge$Pathway_short_name %in% selected_pathways,  ]

#table(meta_feats_rel_merge[,c("Pathway_category2", "Pathway_short_name")])
##
#row.names(meta_feats_rel_merge) = meta_feats_rel_merge$KO_short_name
#meta_feats_rel_merge = meta_feats_rel_merge[order(meta_feats_rel_merge$Pathway_category2), ]
meta_feats_rel_merge = meta_feats_rel_merge[order(meta_feats_rel_merge$Pathway_category2_short, meta_feats_rel_merge$Pathway_short_name), ]


write.csv(meta_feats_rel_merge, file.path(outdir, "meta_feats_rel_heatmap.csv"))
```


```{r}
#print(length(unique(meta_feats_rel_merge$KO_short_name)))
#print(dim(data))
#print(data)
library(ComplexHeatmap)
library(circlize)
#print(unique(meta_feats_rel_merge$Pathway_category1))
#print(unique(meta_feats_rel_merge$Pathway_category2))

#pathways = meta_feats_rel_merge$Pathway_short_name
#pdf(file.path(outdir, paste0("03MaAsLin2_", taxon_type, "_heatmap_with_desc.pdf")), width=8, height=8)
###绘制热图可参考的代码：D:/Zhaolab2020/virome/TGScompare/202205Review/results/Results/00heatmaps.R
##绘制行注释：https://www.biostars.org/p/9526326/
print(sort(table(meta_feats_rel_merge$Pathway_category2_short)))
print(table(meta_feats_rel_merge$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Amino acid metabolism", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Biosynthesis of other secondary metabolites", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Carbohydrate metabolism", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Energy metabolism", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Glycan biosynthesis and metabolism", ]$Pathway_short_name))

print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Metabolism of cofactors and vitamins", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Metabolism of other amino acids", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Nucleotide metabolism", ]$Pathway_short_name))
##"Xenobiotics biodegradation and metabolism"
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Lipid metabolism", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Metabolism of terpenoids and polyketides", ]$Pathway_short_name))
print(table(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_category2_short=="Xenobiotics biodegradation and metabolism", ]$Pathway_short_name))


meta_feats_rel_merge$Pathway_short_name[meta_feats_rel_merge$Pathway_short_name=="Glycosaminoglycan biosynthesis - chondroitin sulfate / dermatan sulfate"] = "Glycosaminoglycan biosynthesis"

meta_feats_rel_merge$Pathway_short_name[meta_feats_rel_merge$Pathway_short_name=="Arabinogalactan biosynthesis - Mycobacterium"] = "Arabinogalactan biosynthesis"

meta_feats_rel_merge$Pathway_short_name[meta_feats_rel_merge$Pathway_short_name=="Phenylalanine, tyrosine and tryptophan biosynthesis"] = "Phe, Tyr and Trp biosynthesis"

meta_feats_rel_merge$Pathway_short_name[meta_feats_rel_merge$Pathway_short_name=="Ubiquinone and other terpenoid-quinone biosynthesis"] = "Terpenoid-quinone biosynthesis"

print(unique(meta_feats_rel_merge$Pathway_short_name))
pathway_levels = c(
                     #维生素和辅因子代谢
                     "Biotin metabolism",
                     "Folate biosynthesis",
                     "Nicotinate and nicotinamide metabolism",
                     "Pantothenate and CoA biosynthesis",
                     "Porphyrin metabolism",
                     "Terpenoid-quinone biosynthesis",
                     
                     ##氨基酸代谢
                     "Arginine and proline metabolism",
                     "Arginine biosynthesis",
                     "Cysteine and methionine metabolism",
                     "Glycine, serine and threonine metabolism",
                     "Histidine metabolism",
                     
                     ##糖代谢
                     "Amino sugar and nucleotide sugar metabolism",
                     "Fructose and mannose metabolism",
                     "Glycolysis / Gluconeogenesis",
                     
                     ##核酸代谢
                     "Purine metabolism",
                     "Pyrimidine metabolism",
                     
                      ##脂质代谢
                     "Fatty acid biosynthesis",
                     "Glycerophospholipid metabolism",

                     ##能量代谢
                     "Oxidative phosphorylation",
                     "Photosynthesis",
                     "Sulfur metabolism",
                     
                     ##外来生物的生物降解和代谢
                     "Benzoate degradation",
                     "Drug metabolism - other enzymes",
                     
                     ##聚糖生物合成和代谢
                     "Lipopolysaccharide biosynthesis"
                     )


unmapped_pathways <- setdiff(unique(meta_feats_rel_merge$Pathway_short_name), pathway_levels)
print(meta_feats_rel_merge[meta_feats_rel_merge$Pathway_short_name %in% unmapped_pathways, ])

meta_feats_rel_merge$Pathway_short_name = factor(meta_feats_rel_merge$Pathway_short_name, levels=pathway_levels)
```
氨基酸代谢，糖类代谢、能量代谢。
```{r}
## 热图中pathway所属类别分类参考: Multi-kingdom microbiota analyses identify bacterial–fungal interactions and ## biomarkers of colorectal cancer across cohorts
title = paste0("Differential KEGG ", taxon_type, " (FDR<0.1)")
width= 5
height= 10
merge_gFC = gFC[, c("SCS", "SCD", "MCI", "AD")]

print(table(meta_feats_rel_merge$Pathway_category2_short))
marker_df_filter = marker_df_filter[meta_feats_rel_merge$feature, ] 
data = meta_feats_rel_merge[, c('SCS', 'SCD', 'MCI', 'AD')]
row.names(data) = meta_feats_rel_merge$KO_short_name

KOs_ha = rowAnnotation(
    category = meta_feats_rel_merge$Pathway_category2_short, 
    col = list(category = c(
                      "Amino acid metabolism" = "#2f9fa0",
                      "Carbohydrate metabolism" = "#f59395",
                      "Energy metabolism" = "#c1702f",
                      "Glycan biosynthesis and metabolism" = "#7fd1e1",
                      #"Biosynthesis of other secondary metabolites" = "#ffc096",
                      #"Metabolism of terpenoids and polyketides" = "#ffc1f6",
                      "Lipid metabolism" = "#b7b43d", 
                      #"Metabolism of other amino acids" = "#6992d8", 
                      "Nucleotide metabolism" = "#fad9c7", 
                      "Xenobiotics biodegradation and metabolism" = "#bbd9f2",
                      "Metabolism of cofactors and vitamins" = "#bf292d"
                      )))
    #annotation_name_side = "right", gp = gpar(col = "black", lwd = 0.5))
#draw(KOs_ha)
#scaled_data = t(scale(t(data)))

col_fun = colorRamp2(c(-0.5, 0, 0.5), colors=c("#4c51a5", "#ffffff","#e53c2d"))
pdf(file.path(outdir, paste0("03MaAsLin2_", taxon_type, "_heatmap_with_desc.pdf")), width=7, height=12)
img <- Heatmap(data, col = col_fun, name = "gFC", column_title = title,
               cell_fun = function(j, i, x, y, width, height, fill) {
                    grid.text(marker_df_filter[i, j], x, y, gp = gpar(fontsize = 8))
               },
               left_annotation = KOs_ha, 
               rect_gp = gpar(col = "black", lwd = 1),
               cluster_rows = FALSE, cluster_columns = FALSE, column_names_rot = 0,
               row_names_side = "right", column_names_side = "bottom", row_title_side = "left", column_title_side = "top",
               row_names_gp = gpar(fontsize=10), 
               column_names_gp = gpar(fontsize=10),
               row_names_max_width = unit(4, "cm"),
               column_title_gp = gpar(fontsize=14),
               row_title_gp = gpar(fontsize=10), 
               row_split = meta_feats_rel_merge$Pathway_short_name,  cluster_row_slices = FALSE, 
               row_gap = unit(1, "mm"),
               row_title_rot = 0, 
               #row_names_max_width = unit(3, "cm"),
               heatmap_legend_param = list(
                   title = "gFC", legend_width = unit(2, "cm"), 
                   position="top",  direction = "horizontal", title_position = "lefttop")
               )
draw(img, padding = unit(c(2, 6, 2, 2), "mm"), heatmap_legend_side="top")
dev.off()
```
################################################################################
差异丰度的KOs数目
################################################################################
```{r}
# imglist = list()
# taxon_types = c("KOs", "GMMs", "GBMs", "pathways")
# for(taxon_type in taxon_types){
#     #taxon_type = taxon_types[i]
#     print(paste0("deal with ", taxon_type))
#     diff_KOs_dir = file.path("D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff", taxon_type)
#     MaAsLin2_stat_file = file.path(diff_KOs_dir, "01up_down_stage.csv")
#     MaAsLin2_stat_df = read.csv(MaAsLin2_stat_file, header=1)
#     
#     MaAsLin2_stat_df$stage = factor(MaAsLin2_stat_df$stage, levels=c("SCS", "SCD", "MCI", "AD"))
#     MaAsLin2_stat_df$change <- factor(MaAsLin2_stat_df$change, levels=c("Depletion", "Elevation"))
#     colors = c("#36bccb", "#ff6836")
#     
#     if(taxon_type=="KOs"){
#         maximum=500; step=100; limit_max=550
#     }else if(taxon_type=="GMMs"){
#         maximum=6; step=2; limit_max=6
#     }else if(taxon_type=="GBMs"){
#         maximum=4; step=1; limit_max=4
#     }else if(taxon_type=="pathways"){
#         maximum=40; step=10; limit_max=40
#     }
#     
#     img <- ggplot(data = MaAsLin2_stat_df, mapping = aes(x = stage, y = count)) +
#         geom_bar(aes(fill=change), stat = 'identity') +
#         scale_fill_manual(values=colors) +
#         labs(title=paste0("Numbers of differential ", taxon_type)) +
#         scale_y_continuous(breaks=seq(0, maximum, step), labels=seq(0,maximum, step), limits=c(0,limit_max)) +
#         theme_bw() + 
#         theme(
#             axis.text.x = element_text(size=12),
#             axis.title.x = element_text(size = 12),
#             axis.text.y = element_text(size = 12),
#             axis.title.y = element_text(size = 12),
#             plot.title = element_text(hjust=0.5, size=16),
#             plot.subtitle = element_text(hjust=0.5, size=12),
#             strip.text.x = element_text(size=12),
#             legend.position = "none",
#             legend.text=element_text(size=10),
#             legend.title=element_text(size=12)
#         )
#     #print(img)
#     imglist[[taxon_type]] <- img
#     pdf(file.path(diff_KOs_dir, paste0("diff_", taxon_type, "_stat.pdf")), width=4, height=4)
#     print(img)
#     dev.off()
# }
```
合并四个图:
```{r}
# library(ggpubr)
# outdir = "D:\\Zhaolab2020\\gut-brain-axis\\metaAD\\01MLmodels\\multikingdom\\03MaAsLin2_diff"
# pdf(file.path(outdir, "diff_functional_features_count_merge.pdf"), width=8, height=6)
# img <- ggarrange(plotlist=imglist, align="hv", nrow=2, ncol=2, labels=letters[1:4], common.legend = TRUE)
# print(img)
# dev.off()
```

